export const fields = [
    {key: 'reference', label: 'Referência'},
    {key: 'transaction', label: 'Transação'},
    {key: 'status', label: 'Status'},
    {key: 'type', label: 'Tipo'},
    {key: 'subtype', label: 'Subtipo'}, 
    {key: 'profile', label: 'Perfil'},
    {key: 'situation', label: 'Situação'},
    {key: 'condominium_name', label: 'Nome do Condomínio'},
    {key: 'block_section_tower', label: 'Quadra/Seção/Torre'},
    {key: 'apartment_store_lot_room', label: 'Apto/Loja/Lote/Sala'},
    {key: 'floor', label: 'Andar'},
    {key: 'blocks_sections_towers_in_condominium', label: 'Quadras/Seções/Torres no Condomínio'},
    {key: 'floors_in_condominium', label: 'Andares no Condomínio'},
    {key: 'units_per_floor_condominium', label: 'Unidades por Andar'},
    {key: 'units_in_condominium', label: 'Unidades no Condomínio'},
    {key: 'state', label: 'Estado'},
    {key: 'city', label: 'Cidade'},
    {key: 'district', label: 'Bairro'},
    {key: 'street', label: 'Rua'},
    {key: 'number', label: 'Número'},
    {key: 'complement', label: 'Complemento'},
    {key: 'area', label: 'Área'},
    {key: 'measurement_unit', label: 'Unidade de Medida'},
    {key: 'bedrooms', label: 'Quartos'},
    {key: 'suites', label: 'Suítes'},
    {key: 'bathrooms', label: 'Banheiros'},
    {key: 'balconies', label: 'Varandas'},
    {key: 'garages', label: 'Vagas'},
    {key: 'covered_garages', label: 'Vagas Cobertas'},
    {key: 'corner_property', label: 'Imóvel de Esquina'},
    {key: 'solar_position', label: 'Posição Solar'},
    {key: 'proximity_to_sea', label: 'Proximidade do Mar'},
    {key: 'subtitle', label: 'Subtítulo'},
    {key: 'property_description', label: 'Descrição do Imóvel'},
    {key: 'condominium_description', label: 'Descrição do Condomínio'},
    {key: 'role', label: 'Função'},
    {key: 'responsible1', label: 'Responsável 1'},
    {key: 'contact_responsible1', label: 'Contato Responsável 1'},
    {key: 'responsible2', label: 'Responsável 2'},
    {key: 'contact_responsible2', label: 'Contato Responsável 2'},
    {key: 'contact_link_responsible2', label: 'Link Contato Responsável 2'},
    {key: 'key_responsible', label: 'Responsável pela Chave'},
    {key: 'contact_key_responsible', label: 'Contato Responsável pela Chave'},
    {key: 'sale_price', label: 'Preço de Venda'},
    {key: 'sale_conditions', label: 'Condições de Venda'},
    {key: 'rental_price', label: 'Preço de Aluguel'},
    {key: 'rental_conditions', label: 'Condições de Aluguel'},
    {key: 'property_tax', label: 'IPTU'},
    {key: 'property_tax_period', label: 'Período IPTU'},
    {key: 'condominium_fee', label: 'Taxa de Condomínio'},
    {key: 'included_in_condominium', label: 'Incluído no Condomínio'},
    {key: 'other_fees', label: 'Outras Taxas'},
    {key: 'fees_description', label: 'Descrição das Taxas'},
    {key: 'deeded', label: 'Escriturado'},
    {key: 'financing_accepted', label: 'Aceita Financiamento'},
    {key: 'has_financing', label: 'Possui Financiamento'},
    {key: 'commission', label: 'Comissão'},
    {key: 'accepts_assets', label: 'Aceita Permuta'},
    {key: 'occupation', label: 'Ocupação'},
    {key: 'exclusive', label: 'Exclusivo'},
    {key: 'notes', label: 'Observações'},
    {key: 'capture_link', label: 'Link de Captura'},
    {key: 'site_link', label: 'Link do Site'},
    {key: 'olx_link', label: 'Link OLX'},
    {key: 'update_message', label: 'Mensagem de Atualização'},
    {key: 'construction_year', label: 'Ano de Construção'},
    {key: 'delivery_forecast', label: 'Previsão de Entrega'},
    {key: 'builder', label: 'Construtora'},
    {key: 'user', label: 'Usuário'},
    {key: 'created_at', label: 'Criado em'},
    {key: 'updated_at', label: 'Atualizado em'}
  ]
